apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo_nodejs_webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo_nodejs_webpage
  template:
    metadata:
      labels:
        app: demo_nodejs_webpage
    spec:
      containers:
      - name: demo_nodejs_webpage
        image: rameshkumarverma/demo_nodejs_webpage:latest 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name:demo_nodejs_webpage-service
spec:
  selector:
    app: demo_nodejs_webpage
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
